// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBywWsFQyc8fJmFJcDpYyKFO8ZqXe-NweE',
    appId: '1:209544392405:ios:763e1d3cb18589d9d9bc5c',
    messagingSenderId: '209544392405',
    projectId: 'smileapp-c6b27',
    authDomain: 'smileapp-c6b27.firebaseapp.com',
    storageBucket: 'smileapp-c6b27.firebasestorage.app',
    measurementId: 'G-CXSW3FTPEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXsFSyZiVHSJccaaFrIaJYOcwMmjymD7M',
    appId: '1:209544392405:android:fd88367cfa4954d10e6c8b',
    messagingSenderId: '209544392405',
    projectId: 'smileapp-c6b27',
    storageBucket: 'smileapp-c6b27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsAHE_l2p0L9SrxAoU4wlpR8hl7qJe-B8',
    appId: '1:209544392405:ios:9d5ec630486732fc0e6c8b',
    messagingSenderId: '209544392405',
    projectId: 'smileapp-c6b27',
    storageBucket: 'smileapp-c6b27.firebasestorage.app',
    iosBundleId: 'com.technocore.smileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsAHE_l2p0L9SrxAoU4wlpR8hl7qJe-B8',
    appId: '1:209544392405:ios:9d5ec630486732fc0e6c8b',
    messagingSenderId: '209544392405',
    projectId: 'smileapp-c6b27',
    storageBucket: 'smileapp-c6b27.firebasestorage.app',
    iosBundleId: 'com.example.aloraapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBywWsFQyc8fJmFJcDpYyKFO8ZqXe-NweE',
    appId: '1:209544392405:web:2ab7d8122979e5fb0e6c8b',
    messagingSenderId: '209544392405',
    projectId: 'smileapp-c6b27',
    authDomain: 'smileapp-c6b27.firebaseapp.com',
    storageBucket: 'smileapp-c6b27.firebasestorage.app',
    measurementId: 'G-0TPESMN8DW',
  );

}